run:
  go: '1.23'
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  goimports:
    local-prefixes: github.com/rhwendt/helios

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
