name: Bug Report
description: Report a bug in Helios
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Flow Enricher
        - Target Generator
        - Runbook Operator
        - Helm Chart
        - Grafana Dashboards
        - Alert Rules
        - ClickHouse Schema
        - Kafka / goflow2
        - Prometheus / Thanos
        - CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Deploy Helios with `values-medium.yaml`
        2. Send NetFlow to goflow2 on port 2055
        3. Check ClickHouse — no rows appear
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output. This will be formatted as code automatically.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Kubernetes version, Helm chart version, cluster type, etc.
      placeholder: |
        - Kubernetes: v1.29.0 (minikube)
        - Helm chart version: 0.1.0
        - Values profile: values-medium.yaml
        - OS: Ubuntu 24.04
    validations:
      required: true
